name: Run Selenium On GitHub Action
on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Selenium
        run: pip install selenium  


      - name: Running the Python script
        run: python Selenium-Template.py
        

